[package]
name = "enigma"
version = "0.1.0"
authors = ["Carlos Diaz-Padron <carlosdiazpadron@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2"
structopt = "0.2"
regex = "1"
serde = "1"
serde_derive = "1"
serde_json = "1"
base64 = "0.10"
